### PR TITLE
[ADAM-610] Revert multiline FASTQ input change

### LINKED ISSUE #610: FASTQ input format picks bad splits
Reported on the [mailing list](https://groups.google.com/forum/#!topic/adam-developers/CMzA8nH7FXg). This seems to be a regression that came in from https://github.com/bigdatagenomics/adam/commit/2052521fba00da4993276161c150bc6b812359c7.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #610. Reverts #551. Adding support for multiline FASTQ input made it difficult to support single line FASTQ. I'd proposed a fix in #611, but it was very slow. I'm in favor of reverting the multiline FASTQ support, since most long read technologies are only emitting single line FASTQ (as far as I can tell).

### CODE REVIEW

File: adam-core/src/main/java/org/bdgenomics/adam/io/InterleavedFastqInputFormat.java [hunk 1]
```diff
@@ -127,13 +123,15 @@ public InterleavedFastqRecordReader(Configuration conf, FileSplit split) throws
          */
         private void positionAtFirstRecord(FSDataInputStream stream) throws IOException {
             Text buffer = new Text();
-            int bytesRead = 0;
-            
+
+            if (true) { // (start > 0) // use start>0 to assume that files start with valid data
```
Comment (tdanford) [inline adam-core/src/main/java/org/bdgenomics/adam/io/InterleavedFastqInputFormat.java]: Just out of curiosity, why is this wrapped in "if (true)"?  Is it just because you're reverting and "this is the way it used to be?"

Comment (fnothaft) [inline adam-core/src/main/java/org/bdgenomics/adam/io/InterleavedFastqInputFormat.java]: Correct. I'm hoping to do more of a cleanup later (e.g., similar to the cleanup that I did in #611), but wanted to get this back to working first.

**Comment by massie** [comment]
Thanks, Frank!
