### PR TITLE
[ADAM-1439] Add inferSequenceDictionary ctr to FeatureRDD.

### LINKED ISSUE #1439: FeatureRDD.apply() does not allow addition of other parameters with defaults in the case class
I blame Scala for this:

Scala will not allow us to have multiple overloaded methods to have parameters with defaults. Currently, we have a default for `storageLevel` in [FeatureRDD Line 117](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala#L117). 

In #1324 we need a default for the partition map when the objects are created shown on [Line 242 of the PR branch](https://github.com/devin-petersohn/adam/blob/partitioner/adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala#L242), so I'm a little stuck. I am getting this error:

`adam/adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala:105: error: in object FeatureRDD, multiple overloaded alternatives of apply define default arguments`

We only have a couple of options and I don't know that I like any of them. @fnothaft @heuermh I'd love some thoughts on this.

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1439.

### CODE REVIEW

File: adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala [hunk 1]
```diff
@@ -49,17 +49,21 @@ class TransformFeaturesArgs extends Args4jBase with ParquetSaveArgs {
...
 
 class TransformFeatures(val args: TransformFeaturesArgs)
     extends BDGSparkCommand[TransformFeaturesArgs] {
   val companion = TransformFeatures
   val storageLevel = StorageLevel.fromString(args.storageLevel)
+  val optStorageLevel = if (args.cache) Some(storageLevel) else None
 
   def run(sc: SparkContext) {
-    sc.loadFeatures(args.featuresFile, storageLevel, None, Option(args.numPartitions))
+    sc.loadFeatures(args.featuresFile, optStorageLevel, None, Option(args.numPartitions))
```
Comment (fnothaft) [inline adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala]: We should use the named syntax (`optStorageLevel = optStorageLevel`) for all of these non-default parameters.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 2]
```diff
@@ -1158,20 +1159,21 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
   def loadGff3(filePath: String,
-               storageLevel: StorageLevel = StorageLevel.MEMORY_ONLY,
+               optStorageLevel: Option[StorageLevel] = Some(StorageLevel.MEMORY_ONLY),
                minPartitions: Option[Int] = None,
                stringency: ValidationStringency = ValidationStringency.LENIENT): FeatureRDD = {
     val records = sc.textFile(filePath, minPartitions.getOrElse(sc.defaultParallelism))
       .flatMap(new GFF3Parser().parse(_, stringency))
     if (Metrics.isRecording) records.instrument() else records
-    FeatureRDD(records, storageLevel)
+    FeatureRDD.inferSequenceDictionary(records, optStorageLevel)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 3]
```diff
@@ -1180,20 +1182,21 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
   def loadGtf(filePath: String,
-              storageLevel: StorageLevel = StorageLevel.MEMORY_ONLY,
+              optStorageLevel: Option[StorageLevel] = Some(StorageLevel.MEMORY_ONLY),
               minPartitions: Option[Int] = None,
               stringency: ValidationStringency = ValidationStringency.LENIENT): FeatureRDD = {
     val records = sc.textFile(filePath, minPartitions.getOrElse(sc.defaultParallelism))
       .flatMap(new GTFParser().parse(_, stringency))
     if (Metrics.isRecording) records.instrument() else records
-    FeatureRDD(records, storageLevel)
+    FeatureRDD.inferSequenceDictionary(records, optStorageLevel)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 4]
```diff
@@ -1202,20 +1205,21 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
   def loadBed(filePath: String,
-              storageLevel: StorageLevel = StorageLevel.MEMORY_ONLY,
+              optStorageLevel: Option[StorageLevel] = Some(StorageLevel.MEMORY_ONLY),
               minPartitions: Option[Int] = None,
               stringency: ValidationStringency = ValidationStringency.LENIENT): FeatureRDD = {
     val records = sc.textFile(filePath, minPartitions.getOrElse(sc.defaultParallelism))
       .flatMap(new BEDParser().parse(_, stringency))
     if (Metrics.isRecording) records.instrument() else records
-    FeatureRDD(records, storageLevel)
+    FeatureRDD.inferSequenceDictionary(records, optStorageLevel)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 5]
```diff
@@ -1224,13 +1228,13 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
   def loadNarrowPeak(filePath: String,
-                     storageLevel: StorageLevel = StorageLevel.MEMORY_ONLY,
+                     optStorageLevel: Option[StorageLevel] = Some(StorageLevel.MEMORY_ONLY),
                      minPartitions: Option[Int] = None,
                      stringency: ValidationStringency = ValidationStringency.LENIENT): FeatureRDD = {
     val records = sc.textFile(filePath, minPartitions.getOrElse(sc.defaultParallelism))
       .flatMap(new NarrowPeakParser().parse(_, stringency))
     if (Metrics.isRecording) records.instrument() else records
-    FeatureRDD(records, storageLevel)
+    FeatureRDD.inferSequenceDictionary(records, optStorageLevel)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 6]
```diff
@@ -1339,24 +1344,24 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
   def loadFeatures(filePath: String,
-                   storageLevel: StorageLevel = StorageLevel.MEMORY_ONLY,
+                   optStorageLevel: Option[StorageLevel] = Some(StorageLevel.MEMORY_ONLY),
                    projection: Option[Schema] = None,
                    minPartitions: Option[Int] = None): FeatureRDD = LoadFeatures.time {
 
     if (filePath.endsWith(".bed")) {
       log.info(s"Loading $filePath as BED and converting to features. Projection is ignored.")
-      loadBed(filePath, storageLevel, minPartitions)
+      loadBed(filePath, optStorageLevel, minPartitions)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 7]
```diff
@@ -1339,24 +1344,24 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
     } else if (filePath.endsWith(".gff3")) {
       log.info(s"Loading $filePath as GFF3 and converting to features. Projection is ignored.")
-      loadGff3(filePath, storageLevel, minPartitions)
+      loadGff3(filePath, optStorageLevel, minPartitions)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 8]
```diff
@@ -1339,24 +1344,24 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
     } else if (filePath.endsWith(".gtf") ||
       filePath.endsWith(".gff")) {
       log.info(s"Loading $filePath as GTF/GFF2 and converting to features. Projection is ignored.")
-      loadGtf(filePath, storageLevel, minPartitions)
+      loadGtf(filePath, optStorageLevel, minPartitions)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala [hunk 9]
```diff
@@ -1339,24 +1344,24 @@ class ADAMContext(@transient val sc: SparkContext) extends Serializable with Log
...
     } else if (filePath.endsWith(".narrowPeak") ||
       filePath.endsWith(".narrowpeak")) {
       log.info(s"Loading $filePath as NarrowPeak and converting to features. Projection is ignored.")
-      loadNarrowPeak(filePath, storageLevel, minPartitions)
+      loadNarrowPeak(filePath, optStorageLevel, minPartitions)
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala]: Ditto here RE: named parameter.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala [hunk 10]
```diff
@@ -109,15 +109,17 @@ object FeatureRDD {
...
-  def apply(
+  def inferSequenceDictionary(
     rdd: RDD[Feature],
-    storageLevel: StorageLevel = StorageLevel.MEMORY_ONLY): FeatureRDD = BuildSequenceDictionary.time {
+    optStorageLevel: Option[StorageLevel]): FeatureRDD = BuildSequenceDictionary.time {
 
-    // cache the rdd, since we're making multiple passes
-    rdd.persist(storageLevel)
+    // optionally cache the rdd, since we're making multiple passes
+    optStorageLevel.map(
```
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala]: `s/map/foreach/g`

Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala]: Also, I'd make this a single line, since it's pretty short.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala [hunk 11]
```diff
@@ -129,7 +129,7 @@ class ADAMContextSuite extends ADAMFunSuite {
 
   sparkTest("Can read a .bed file without cache") {
     val path = testFile("gencode.v7.annotation.trunc10.bed")
-    val features: RDD[Feature] = sc.loadFeatures(path, StorageLevel.NONE).rdd
+    val features: RDD[Feature] = sc.loadFeatures(path, Some(StorageLevel.NONE)).rdd
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala [hunk 12]
```diff
@@ -50,7 +50,7 @@ class CoverageRDDSuite extends ADAMFunSuite {
     val f2 = Feature.newBuilder().setContigName("chr1").setStart(15).setEnd(20).setScore(2.0).build()
     val f3 = Feature.newBuilder().setContigName("chr2").setStart(15).setEnd(20).setScore(2.0).build()
 
-    val featureRDD: FeatureRDD = FeatureRDD(sc.parallelize(Seq(f1, f2, f3)))
+    val featureRDD: FeatureRDD = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f1, f2, f3)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala [hunk 13]
```diff
@@ -71,7 +71,7 @@ class CoverageRDDSuite extends ADAMFunSuite {
...
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala [hunk 14]
```diff
@@ -100,7 +100,7 @@ class CoverageRDDSuite extends ADAMFunSuite {
     val f2 = Feature.newBuilder().setContigName("chr1").setStart(5).setEnd(7).setScore(3.0).build()
     val f3 = Feature.newBuilder().setContigName("chr1").setStart(7).setEnd(20).setScore(4.0).build()
 
-    val featureRDD: FeatureRDD = FeatureRDD(sc.parallelize(Seq(f1, f2, f3)))
+    val featureRDD: FeatureRDD = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f1, f2, f3)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala [hunk 15]
```diff
@@ -417,7 +417,7 @@ class FeatureRDDSuite extends ADAMFunSuite with TypeCheckedTripleEquals {
     val f6 = fb.setContigName("1").setStart(10L).setEnd(110L).clearStrand().build() // null strand last
     val f7 = fb.setContigName("2").build()
 
-    val features = FeatureRDD(sc.parallelize(Seq(f7, f6, f5, f4, f3, f2, f1)))
+    val features = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f7, f6, f5, f4, f3, f2, f1)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala [hunk 16]
```diff
@@ -439,7 +439,7 @@ class FeatureRDDSuite extends ADAMFunSuite with TypeCheckedTripleEquals {
     val f6 = fb.setScore(0.9).build() // Double defaults to increasing sort order
     val f7 = fb.clearScore().build() // nulls last
 
-    val features = FeatureRDD(sc.parallelize(Seq(f7, f6, f5, f4, f3, f2, f1)))
+    val features = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f7, f6, f5, f4, f3, f2, f1)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala [hunk 17]
```diff
@@ -457,7 +457,7 @@ class FeatureRDDSuite extends ADAMFunSuite with TypeCheckedTripleEquals {
     val f2 = fb.setGeneId("gene2").build()
     val f3 = fb.clearGeneId().build() // nulls last
 
-    val features = FeatureRDD(sc.parallelize(Seq(f3, f2, f1)))
+    val features = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f3, f2, f1)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala [hunk 18]
```diff
@@ -473,7 +473,7 @@ class FeatureRDDSuite extends ADAMFunSuite with TypeCheckedTripleEquals {
     val f4 = fb.setGeneId("gene2").setTranscriptId("transcript2").build()
     val f5 = fb.setGeneId("gene2").clearTranscriptId().build() // nulls last
 
-    val features = FeatureRDD(sc.parallelize(Seq(f5, f4, f3, f2, f1)))
+    val features = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f5, f4, f3, f2, f1)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala [hunk 19]
```diff
@@ -495,7 +495,7 @@ class FeatureRDDSuite extends ADAMFunSuite with TypeCheckedTripleEquals {
     val f8 = fb.setGeneId("gene2").setTranscriptId("transcript1").setAttributes(ImmutableMap.of("rank", "2")).build()
     val f9 = fb.setGeneId("gene2").setTranscriptId("transcript1").clearAttributes().build() // nulls last
 
-    val features = FeatureRDD(sc.parallelize(Seq(f9, f8, f7, f6, f5, f4, f3, f2, f1)))
+    val features = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f9, f8, f7, f6, f5, f4, f3, f2, f1)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala [hunk 20]
```diff
@@ -517,7 +517,7 @@ class FeatureRDDSuite extends ADAMFunSuite with TypeCheckedTripleEquals {
     val f4 = fb.setAttributes(ImmutableMap.of("rank", "2")).build()
     val f5 = fb.clearAttributes().build() // nulls last
 
-    val features = FeatureRDD(sc.parallelize(Seq(f5, f4, f3, f2, f1)))
+    val features = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f5, f4, f3, f2, f1)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala]: Ditto here RE: named parameter.

File: adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala [hunk 21]
```diff
@@ -532,7 +532,7 @@ class FeatureRDDSuite extends ADAMFunSuite with TypeCheckedTripleEquals {
     val f2 = Feature.newBuilder().setContigName("chr1").setStart(15).setEnd(20).setScore(2.0).build()
     val f3 = Feature.newBuilder().setContigName("chr2").setStart(15).setEnd(20).setScore(2.0).build()
 
-    val featureRDD: FeatureRDD = FeatureRDD(sc.parallelize(Seq(f1, f2, f3)))
+    val featureRDD: FeatureRDD = FeatureRDD.inferSequenceDictionary(sc.parallelize(Seq(f1, f2, f3)), None)
```
Comment (fnothaft) [inline adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala]: Ditto here RE: named parameter.

**Comment by fnothaft** [comment]
Merged! Thanks @heuermh!
