### PR TITLE
[ADAM-1308] Fix stack overflow in join with custom iterator impl.

### LINKED ISSUE #1308: Lineage for partitionAndJoin in ShuffleRegionJoin causes StackOverflow Errors
I am having issues with partitionAndJoin for LeftOuterShuffleRegionJoin. There is a stack overflow issue. I can oddly avoid this issue by putting counts in partitionAndJoin() after operations, if the inputs are cached.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1308. CC @akmorrow13 @devin-petersohn

### CODE REVIEW

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala [hunk 1]
```diff
@@ -263,6 +263,30 @@ private[rdd] case class ManualRegionPartitioner(partitions: Int) extends Partiti
   }
 }
 
+private class AppendableIterator[T] extends Iterator[T] {
+  var iterators: ListBuffer[Iterator[T]] = ListBuffer.empty
```
Comment (heuermh) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala]: Do you need to worry about thread safety?  Would immutable copy-on-write help here?

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala [hunk 2]
```diff
@@ -263,6 +263,30 @@ private[rdd] case class ManualRegionPartitioner(partitions: Int) extends Partiti
...
+
+  def append(iter: Iterator[T]) {
+    if (iter.hasNext) {
+      iterators += iter
```
Comment (heuermh) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala]: safe copy?  `iter` could be modified by the caller

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala [hunk 3]
```diff
@@ -263,6 +263,30 @@ private[rdd] case class ManualRegionPartitioner(partitions: Int) extends Partiti
...
+    }
+  }
+
+  def hasNext: Boolean = {
+    iterators.nonEmpty
```
Comment (heuermh) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala]: shouldn't this query all of the iterators in `iterators`?

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala (hunk 1 above)
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala]: Nah, this is only accessed inside of a single thread.

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala (hunk 2 above)
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala]: In general, Scala has a pretty strict "advisory" (not quite a contract?) on using [Iterators](http://www.scala-lang.org/api/2.10.3/index.html#scala.collection.Iterator):

> It is of particular importance to note that, unless stated otherwise, one should never use an iterator after calling a method on it.

This is a private class used only in this file, so I think it is OK to make the assumption that `iter` is not modified after being passed.

**Comment by akmorrow13** [comment]
I was going to try running this on the problem before it's merged unless anyone deems that unnecessary.

**Comment by fnothaft** [comment]
> I was going to try running this on the problem before it's merged unless anyone deems that unnecessary.

I would really like that so we can confirm that this is a fix before we merge.

**Comment by devin-petersohn** [comment]
I computed on the same code as before, and did not run into stack overflow errors. I think we can go forward with the merge.

**Comment by akmorrow13** [comment]
I reran my pipeline and it looks good. Thanks @fnothaft !

**Comment by heuermh** [comment]
Thank you for confirming, @devin-petersohn @akmorrow13

**Comment by heuermh** [comment]
Thank you, @fnothaft
