### PR TITLE
[ADAM-646] Special case reads with '*' quality during BQSR.

### LINKED ISSUE #646: Requirement failed warning while running BQSR @DecadentRead
When running BQSR with the following command,

adam-submit transform /small.adam /small_bqsr.adam -recalibrate_base_qualities -known_snps /db/dbsnp_137.hg19.excluding_sites_after_129.vcf --master yarn-client --num-executors 85

I still got the following 'requirement failed Error' in the DecadentRead and there is no output for the BQSR.

15/04/09 13:58:17 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 18, node-119): java.lang.IllegalArgumentException: Error "requirement failed: sequence and qualityScores must be same length" while constructing DecadentRead from Read({"contig": {"contigName": "1", "contigLength": 249250621, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null}, "start": 26472783, "oldPosition": null, "end": 26472858, "mapq": 60, "readName": "simread:1:26472783:false", "sequence": "GTATAAGAGCAGCCTTATTCCTATTTATAATCAGGGTGAAACACCTGTGCCAATGCCAAGACAGGGGTGCCAAGA", "qual": "*", "cigar": "75M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "firstOfPair": false, "secondOfPair": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": true, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": null, "origQual": null, "attributes": "XS:i:0\tAS:i:75\tNM:i:0", "recordGroupName": null, "recordGroupSequencingCenter": null, "recordGroupDescription": null, "recordGroupRunDateEpoch": null, "recordGroupFlowOrder": null, "recordGroupKeySequence": null, "recordGroupLibrary": null, "recordGroupPredictedMedianInsertSize": null, "recordGroupPlatform": null, "recordGroupPlatformUnit": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContig": null})
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:40)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:32)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:901)
	at org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:901)
	at org.apache.spark.SparkContext$$anonfun$29.apply(SparkContext.scala:1355)
	at org.apache.spark.SparkContext$$anonfun$29.apply(SparkContext.scala:1355)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: requirement failed: sequence and qualityScores must be same length
	at scala.Predef$.require(Predef.scala:233)
	at org.bdgenomics.adam.rich.DecadentRead.<init>(DecadentRead.scala:61)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:36)
	... 23 more

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #646. Allows the creation of `DecadentRead`s with `*` quality scores. These reads are then not observed or corrected during BQSR.

### CODE REVIEW

**Comment by massie** [comment]
This looks good, but should we just set `qualityString` to `null` if it's `*` and then just do a `null` check?

**Comment by fnothaft** [comment]
Are you suggesting to do that check in the SAM/BAM<->ADAM converters?

**Comment by massie** [comment]
Yes, when we convert from BAM to ADAM, set simply set the `qualityString` to `null`, if it's `*`. It will be more compact (we save two bytes for each read) and doesn't require any string comparisons (albeit the string isn't very long :)).

**Comment by fnothaft** [comment]
That's a good idea. Let me refactor that.

**Comment by fnothaft** [comment]
Updated with the `null` on conversion change.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

Looks like some issue with a JAR not being pulled down in the Hadoop 2.2 build.

File: adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala [hunk 1]
```diff
@@ -79,7 +79,7 @@ class AlignmentRecordConverter extends Serializable {
     // set canonically necessary fields
     builder.setReadName(adamRecord.getReadName.toString)
     builder.setReadString(adamRecord.getSequence)
-    builder.setBaseQualityString(adamRecord.getQual)
+    Option(adamRecord.getQual).fold(builder.setBaseQualityString("*"))(s => builder.setBaseQualityString(s))
```
Comment (massie) [inline adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala]: Simple pattern matching here would prevent double-setting the qualityString (unless I'm misreading this) and prevent allocating objects we won't use.

Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala]: Ah, sure.

**Comment by massie** [comment]
Other than one nit, this looks good to me.

File: adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala (hunk 1 above)
Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala]: Fixed.

**Comment by massie** [comment]
Thanks, Frank!

**Comment by Jaeki** [comment]
Thanks, Frank! 
I have tested in my cluster with small data, it works well.

**Comment by fnothaft** [comment]
Great! Glad to hear it @Jaeki!

**Comment by Jaeki** [comment]
@fnothaft Could you check the followin case?
I got the similar error when running BQSR, The input sam file is the aligned with SNAP (NA12878).

15/04/11 12:35:38 INFO DAGScheduler: Job 1 failed: aggregate at BaseQualityRecalibration.scala:84, took 3.648340 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 45 in stage 1.0 failed 4 times, most recent failure: Lost task 45.3 in stage 1.0 (TID 111, node-120): java.lang.IllegalArgumentException: Error "requirement failed" while constructing DecadentRead from Read({"contig": {"contigName": "chrY", "contigLength": 59373566, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null}, "start": 13833306, "oldPosition": null, "end": 13833411, "mapq": 23, "readName": "ERR032977_24245808", "sequence": "AAATGGAACGAAGTGGAATCGAGTGGAATGGAATCGAATGGAGTGAAATGGAATGGAATGGACGCGAAAGAATGGACTGGAACAAAATGAAATCGAACGGT", "qual": "CCCCCCCCCCCCCCCCCBCCCCCDCCCCCCCDCCCC@DCCCBCBCBBBCCCABCCCBDBCCDCCBCABBC?@@A@BABBBDBD@D<8;BB8?:@@D@B>>1", "cigar": "69M1D35=", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": true, "properPair": true, "readMapped": true, "mateMapped": true, "firstOfPair": false, "secondOfPair": true, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": false, "mateNegativeStrand": true, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": null, "origQual": null, "attributes": "PU:Z:pu\tSM:Z:sm\tNM:i:14\tPL:Z:Illumina\tRG:Z:FASTQ\tPG:Z:SNAP\tLB:Z:lb", "recordGroupName": "FASTQ", "recordGroupSequencingCenter": null, "recordGroupDescription": null, "recordGroupRunDateEpoch": null, "recordGroupFlowOrder": null, "recordGroupKeySequence": null, "recordGroupLibrary": "lb", "recordGroupPredictedMedianInsertSize": null, "recordGroupPlatform": "Illumina", "recordGroupPlatformUnit": "pu", "recordGroupSample": "sm", "mateAlignmentStart": 13869382, "mateAlignmentEnd": null, "mateContig": {"contigName": "chrY", "contigLength": 59373566, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null}})
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:40)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:32)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:901)
	at org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:901)
	at org.apache.spark.SparkContext$$anonfun$29.apply(SparkContext.scala:1355)
	at org.apache.spark.SparkContext$$anonfun$29.apply(SparkContext.scala:1355)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:221)
	at org.bdgenomics.adam.rich.DecadentRead.<init>(DecadentRead.scala:71)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:36)
	... 23 more

**Comment by massie** [comment]
The exact line of the error is shown in this stack trace.

```
at org.bdgenomics.adam.rich.DecadentRead.(DecadentRead.scala:71)
```

Your sequence is 102 bases long...

```bash 
$ echo "AAATGGAACGAAGTGGAATCGAGTGGAATGGAATCGAATGGAGTGAAATGGAATGGAATGGACGCGAAAGAATGGACTGGAACAAAATGAAATCGAACGGT" | wc -c
102
```

... but the difference between your reference start and end position is `13833411 - 13833306 = 105`. The cigar string is `69M1D35=` which agrees with the sequence length `69+1+35 = 105`.

The sequence is missing 3 bases.

**Comment by Jaeki** [comment]
@massie Thank you for your comment. Do you think the missing 3 bases come from the SNAP tool ?
