### PR TITLE
[ADAM-1914] Python profile needs to be specified for egg to be in distribution.

### LINKED ISSUE #1914: cannot run pyadam from adam distribution 0.23.0
generates error org.apache.spark.SparkException: Added file file:adam-distribution-spark2_2.11-0.23.0/repo is a directory and recursive is not turned on.

This is because the adam egg file does not exist in the repo directory.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1914.

### CODE REVIEW

File: scripts/release/release.sh [hunk 1]
```diff
@@ -29,7 +29,7 @@ git push origin ${branch}
 git checkout -b maint_spark2_2.11-${release} ${branch}
 git commit -a -m "Modifying pom.xml files for Spark 2, Scala 2.11 release."
 mvn --batch-mode \
-  -P distribution \
+  -P python,r,distribution \
```
Comment (heuermh) [inline scripts/release/release.sh]: On further consideration, this won't work, will it?  The only way I get the python and r profiles to build for me locally is to run separate mvn steps after first running mvn install, and then specify all the `PY4J_ZIP PYSPARK_SUBMIT_ARGS` etc. environment variables.

**Comment by heuermh** [comment]
Thank you, @fnothaft
