### PR TITLE
Miscellaneous VCF fixes

### LINKED ISSUE #1202: gVCF - can't load multi-allelic sites
I'm trying to input the file:
http://bioinformaticstools.mayo.edu/research/wp-content/plugins/download.php?url=https://s3-us-west-2.amazonaws.com/mayo-bic-tools/variant_miner/gvcfs/NA12878.chr22.g.vcf.gz

I believe I solved the SB tag problem of #1199 

However, now on the VCF row below I get the following error:

```
chr22   18027817        .       CTTTT   C,CT,CTT,CTTT,<NON_REF> 1364.73 .       DP=78;MLEAC=0,0,1,1,0;MLEAF=0.00,0.00,0.500,0.500,0.00;MQ=70.00;MQ0=0   GT:AD:DP:GQ:PL:SB       3/4:0,4,6,28,17,0:55:99:1402,1244,2007,972,1382,1297,371,355,301,301,792,617,486,0,653,1038,1016,883,315,597,935:0,0,14,3
```

Note, clearly the row above is not a reference block, it is called multi-allelic site within the gVCF file 

```
 x2.rdd.count
2016-10-08 13:04:26 ERROR Executor:95 - Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.IllegalArgumentException: Multi-allelic site with non-ref symbolic allele[VC Unknown @ chr22:18027817-18027821 Q1364.73 of type=MIXED alleles=[CTTTT*, <NON_REF>, C, CT, CTT, CTTT] attr={DP=78, MLEAC=[0, 0, 1, 1, 0], MLEAF=[0.00, 0.00, 0.500, 0.500, 0.00], MQ=70.00, MQ0=0} GT=GT:AD:DP:GQ:PL:SB 3/4:0,4,6,28,17,0:55:99:1402,1244,2007,972,1382,1297,371,355,301,301,792,617,486,0,653,1038,1016,883,315,597,935:0,0,14,3
    at org.bdgenomics.adam.converters.VariantContextConverter.convert(VariantContextConverter.scala:214)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadVcf$1.apply(ADAMContext.scala:823)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadVcf$1.apply(ADAMContext.scala:823)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1595)
    at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1157)
    at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1157)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2016-10-08 13:04:26 WARN  TaskSetManager:70 - Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.IllegalArgumentException: Multi-allelic site with non-ref symbolic allele[VC Unknown @ chr22:18027817-18027821 Q1364.73 of type=MIXED alleles=[CTTTT*, <NON_REF>, C, CT, CTT, CTTT] attr={DP=78, MLEAC=[0, 0, 1, 1, 0], MLEAF=[0.00, 0.00, 0.500, 0.500, 0.00], MQ=70.00, MQ0=0} GT=GT:AD:DP:GQ:PL:SB    3/4:0,4,6,28,17,0:55:99:1402,1244,2007,972,1382,1297,371,355,301,301,792,617,486,0,653,1038,1016,883,315,597,935:0,0,14,3
    at org.bdgenomics.adam.converters.VariantContextConverter.convert(VariantContextConverter.scala:214)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadVcf$1.apply(ADAMContext.scala:823)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadVcf$1.apply(ADAMContext.scala:823)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at org.apache.spark.util.Utils$.getIterat
```

exception is from:
https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala#L214

### PR DESCRIPTION
**Pull request by fnothaft**
Fixes #1202, #1226, #1232, supersedes #1205.

### CODE REVIEW

File: adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala [hunk 1]
```diff
@@ -52,9 +52,14 @@ class ADAM2VcfArgs extends Args4jBase with ParquetArgs {
   @Args4jOption(required = false, name = "-coalesce", usage = "Set the number of partitions written to the ADAM output directory")
   var coalesce: Int = -1
 
-  @Args4jOption(required = false, name = "-sort_on_save", usage = "Sort the VCF output.")
+  @Args4jOption(required = false, name = "-sort_on_save", usage = "Sort the VCF output by contig index.")
   var sort: Boolean = false
 
+  @Args4jOption(required = false,
+    name = "-sort_lexicographically_on_save",
+    usage = "Sort the VCF output by lexicographic order. Conflicts with -sort_on_save.")
```
Comment (heuermh) [inline adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala]: Is there any possibility of a third sort method?  If so, maybe separate `-sort_on_save` and `-sort_by [method]` arguments would be preferrable

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala [hunk 2]
```diff
@@ -111,9 +112,18 @@ case class VariantContextRDD(rdd: RDD[VariantContext],
...
+   * @param sortLexicographically If true and sortOnSave is true, the variants
+   *   will be sorted by lexicographically ordered contig name, instead of by
+   *   sequence index order. If sortOnSave is false, this parameter is ignored.
+   *   Default is false (use contig index order).
+   * @param asSingleFile If true, saves the output as a single file by merging
+   *   the sharded output after completing the write to HDFS. If false, the
+   *   output of this call will be written as shards, where each shard has a
+   *   valid VCF header. Default is false.
    */
   def saveAsVcf(filePath: String,
```
Comment (heuermh) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala]: too many boolean parameters here

Comment (fnothaft) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala]: I kinda agree. I think it would probably make sense to break this out as is done with `AlignmentRecord`s and have `sortByXYZ` functions.

File: adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala (hunk 1 above)
Comment (fnothaft) [inline adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala]: I can't think of one...

File: adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala (hunk 2 above)
Comment (heuermh) [inline adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala]: +1

**Comment by heuermh** [comment]
Thank you, @fnothaft
